### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by hirschferkel** [jnga/ReadableMail#1]
regarding https://github.com/jnga/ReadableMail
the installation of the installler states that it can't finish the operation.

Trying 
sudo cat /Users/[username]/Desktop/ReadableMail-1.1/message-style-overrides.css >> /Applications/Mail.app/Contents/Resources/Message.css
-bash: /Applications/Mail.app/Contents/Resources/Message.css: Operation not permitted

Trying to work like http://apple.stackexchange.com/questions/157104/can-i-increase-the-minimum-font-size-of-text-when-reading-html-messages-in-mail

tells me that i'm not part of the group "system Wheel" so i can't chenge the file. Any idea how i can edit the css-file?

Best

**Comment by jnga** [comment]
OS X 10.11 has a new feature called System Integrity Protection (SIP) which prevents modifying system files, so the installer cannot do what it needs to do. So this project only works with OS X up to 10.10. It might work with SIP disabled, but I have not tried that and have decided not to pursue it.
